/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe Project */
        post: operations["transcribe_project_api_v1_projects__project_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/raw-transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Raw Transcript */
        get: operations["get_raw_transcript_api_v1_projects__project_id__raw_transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/ecs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ecs */
        get: operations["get_ecs_api_v1_projects__project_id__ecs_get"];
        /** Put Ecs */
        put: operations["put_ecs_api_v1_projects__project_id__ecs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Style */
        get: operations["get_style_api_v1_projects__project_id__style_get"];
        /** Put Style */
        put: operations["put_style_api_v1_projects__project_id__style_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/recalculate-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate Groups */
        post: operations["recalculate_groups_api_v1_projects__project_id__recalculate_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/reset-to-raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset To Raw */
        post: operations["reset_to_raw_api_v1_projects__project_id__reset_to_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project */
        post: operations["export_project_api_v1_projects__project_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/export-srt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project Srt */
        post: operations["export_project_srt_api_v1_projects__project_id__export_srt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_project_api_v1_projects_post */
        Body_create_project_api_v1_projects_post: {
            /** File */
            file: string;
            /** Name */
            name?: string | null;
            /** Language */
            language?: string | null;
        };
        /** Bounds */
        Bounds: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /**
         * CaptionAnimation
         * @description Cosmetic entrance transition, orthogonal to `RevealMode` - which
         *     word(s) exist vs. how the segment transitions on screen (INVARIANTS
         *     S8). No bounds check, same treatment as `textTransform`/`italic`/
         *     `glow`.
         * @enum {string}
         */
        CaptionAnimation: "none" | "fade" | "pop" | "bounce" | "blur" | "snap";
        /** CaptionStyleSpec */
        CaptionStyleSpec: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Presetid
             * Format: uuid
             */
            presetId: string;
            /**
             * Perphrasestyle
             * @default false
             */
            perPhraseStyle: boolean;
            /** @default {} */
            overrides: components["schemas"]["StyleOverrides"];
        };
        /**
         * CaptionStyleSpecPutBody
         * @description Same shape as CaptionStyleSpec minus project_id/owner_id (contract §8).
         */
        CaptionStyleSpecPutBody: {
            /**
             * Presetid
             * Format: uuid
             */
            presetId: string;
            /**
             * Perphrasestyle
             * @default false
             */
            perPhraseStyle: boolean;
            /** @default {} */
            overrides: components["schemas"]["StyleOverrides"];
        };
        /** ECS */
        ECS: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Segments */
            segments: components["schemas"]["Segment"][];
        };
        /**
         * ECSPutBody
         * @description Same shape as ECS minus project_id/owner_id — those come from the URL/
         *     session, not the client (contract §7).
         */
        ECSPutBody: {
            /** Segments */
            segments: components["schemas"]["Segment"][];
        };
        /**
         * ExportRequestBody
         * @description Carries the whole ECS + style documents, not just a project id — export
         *     must reflect exactly what's on screen, not stale backend state (contract
         *     §12). Shared verbatim by `POST /export` and `POST /export-srt` — both
         *     need the same ecs/style to do their respective jobs, and a second,
         *     structurally identical schema would just be one more thing that can
         *     drift from this one.
         */
        ExportRequestBody: {
            ecs: components["schemas"]["ECSPutBody"];
            style: components["schemas"]["CaptionStyleSpecPutBody"];
        };
        /** ExportResult */
        ExportResult: {
            /** Video Url */
            video_url: string;
        };
        /** ExportSrtResult */
        ExportSrtResult: {
            /** Srt Url */
            srt_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            progress: components["schemas"]["JobProgress"] | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Error */
            error: string | null;
            /** Result */
            result: components["schemas"]["ExportResult"] | components["schemas"]["ExportSrtResult"] | null;
        };
        /**
         * JobProgress
         * @description Best-effort "current bottleneck" signal across the transcribe job's
         *     four parallel branches (arch §2.8) — meaningful only while
         *     status="processing", null at every other status.
         * @enum {string}
         */
        JobProgress: "preparing" | "transcribing" | "generating_preview";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "processing" | "done" | "failed";
        /**
         * JobType
         * @description `export_srt` shares the `export` queue (INVARIANTS P5, X6) - it is not
         *     a third queue, just a second job type on an existing one. The LLM smart
         *     re-splitter (Step 14, arch §5.3) has no `JobType`/queue of its own - it
         *     runs as a plain awaited function call inside `transcribe_task`, not a
         *     dispatched task, since it blocks that job's own `done` transition either
         *     way (no race with the user starting to edit) and a separate queue bought
         *     no real concurrency for work that's awaited synchronously regardless.
         * @enum {string}
         */
        JobType: "transcribe" | "export" | "export_srt";
        /**
         * OutlineOrShadow
         * @description Shared shape for `outline`/`shadow` (contract §8). `size` and `color`
         *     have no bounds check (INVARIANTS S6) — any value from the type is
         *     valid. `alpha` validates against a fixed 0-100 range, not per-preset
         *     bounds, unlike fontSize/verticalPosition/safeArea (L8).
         */
        OutlineOrShadow: {
            size: components["schemas"]["OutlineShadowSize"];
            /** Color */
            color: string;
            /** Alpha */
            alpha: number;
        };
        /**
         * OutlineShadowSize
         * @enum {string}
         */
        OutlineShadowSize: "none" | "small" | "medium" | "large";
        /**
         * PolymorphicJobResponse
         * @description 202 branch — the active splitter is expensive. Shared shape for both
         *     recalculate-groups and reset-to-raw (contract §10, §11). Never exercised by
         *     the MVP splitter today (INVARIANTS P5).
         */
        PolymorphicJobResponse: {
            job: components["schemas"]["Job"];
        };
        /**
         * Preset
         * @description No owner_id — presets are shared system templates, not user content
         *     (contract §1, §9).
         */
        Preset: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Default */
            default: boolean;
            base: components["schemas"]["PresetBase"];
            bounds: components["schemas"]["PresetBounds"];
        };
        /**
         * PresetBase
         * @description Always fully populated, unlike StyleOverrides — a preset defines a
         *     complete style, not a sparse delta.
         */
        PresetBase: {
            /** Fontsize */
            fontSize: number;
            /** Fontfamily */
            fontFamily: string;
            /** Fontweight */
            fontWeight: number | string;
            /** Color */
            color: string;
            /** Highlightcolors */
            highlightColors: string[];
            textTransform: components["schemas"]["TextTransform"];
            /** Italic */
            italic: boolean;
            /** Glow */
            glow: boolean;
            outline: components["schemas"]["OutlineOrShadow"] | null;
            shadow: components["schemas"]["OutlineOrShadow"] | null;
            /** Showpunctuation */
            showPunctuation: boolean;
            revealMode: components["schemas"]["RevealMode"];
            captionAnimation: components["schemas"]["CaptionAnimation"];
            /** Verticalposition */
            verticalPosition: number;
            safeArea: components["schemas"]["SafeArea"];
        };
        /**
         * PresetBounds
         * @description No entry for outline/shadow/glow/textTransform — they have no
         *     per-preset bounds at all (INVARIANTS S6, arch §10).
         */
        PresetBounds: {
            fontSize: components["schemas"]["Bounds"];
            verticalPosition: components["schemas"]["Bounds"];
            safeArea: components["schemas"]["SafeAreaBounds"];
        };
        /** Project */
        Project: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Name */
            name: string;
            /** Video Url */
            video_url: string;
            /** Language */
            language: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Preview Video Url */
            preview_video_url: string | null;
            /** Video Width */
            video_width: number | null;
            /** Video Height */
            video_height: number | null;
            /** Video Duration Seconds */
            video_duration_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Transcribe Job Id */
            latest_transcribe_job_id: string | null;
            /** Export Job Ids */
            export_job_ids: string[];
        };
        /** RawTranscript */
        RawTranscript: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Words */
            words: components["schemas"]["RawTranscriptWord"][];
            /** Language */
            language?: string | null;
        };
        /**
         * RawTranscriptWord
         * @description No `id` — raw-transcript words carry no link back from the ECS (INVARIANTS D2).
         */
        RawTranscriptWord: {
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /**
         * RecalculateGroupsRequest
         * @description Carries the live frontend Words[], not just a project id — this endpoint
         *     must operate on unsaved edits too (contract §10).
         */
        RecalculateGroupsRequest: {
            /** Words */
            words: components["schemas"]["Word"][];
        };
        /**
         * RecalculateGroupsResult
         * @description 200 branch — the active splitter is cheap (MVP default).
         */
        RecalculateGroupsResult: {
            /** Segments */
            segments: components["schemas"]["Segment"][];
        };
        /**
         * ResetToRawResult
         * @description 200 branch — same shape as GET /ecs (contract §11).
         */
        ResetToRawResult: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Segments */
            segments: components["schemas"]["Segment"][];
        };
        /**
         * RevealMode
         * @enum {string}
         */
        RevealMode: "phrase" | "progressive" | "single-word";
        /** SafeArea */
        SafeArea: {
            /** Top */
            top: number;
            /** Bottom */
            bottom: number;
        };
        /** SafeAreaBounds */
        SafeAreaBounds: {
            top: components["schemas"]["Bounds"];
            bottom: components["schemas"]["Bounds"];
        };
        /**
         * Segment
         * @description No `start`/`end` — segment bounds are derived from words, never stored
         *     (INVARIANTS D5). `overrides` is the one deliberate exception to Data
         *     never carrying Style (INVARIANTS D11, arch §4.2) — only meaningful when
         *     the project's `CaptionStyleSpec.perPhraseStyle` is true.
         */
        Segment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Words */
            words: components["schemas"]["Word"][];
            overrides?: components["schemas"]["StyleOverrides"] | null;
        };
        /**
         * StyleOverrides
         * @description Sparse by design — only fields that differ from the preset's base values
         *     need to be present (contract §8). No `horizontalAlign` (INVARIANTS L5).
         */
        StyleOverrides: {
            /** Fontsize */
            fontSize?: number | null;
            /** Fontfamily */
            fontFamily?: string | null;
            /** Fontweight */
            fontWeight?: number | string | null;
            /** Color */
            color?: string | null;
            /** Highlightcolors */
            highlightColors?: string[] | null;
            textTransform?: components["schemas"]["TextTransform"] | null;
            /** Italic */
            italic?: boolean | null;
            /** Glow */
            glow?: boolean | null;
            outline?: components["schemas"]["OutlineOrShadow"] | null;
            shadow?: components["schemas"]["OutlineOrShadow"] | null;
            /** Showpunctuation */
            showPunctuation?: boolean | null;
            revealMode?: components["schemas"]["RevealMode"] | null;
            captionAnimation?: components["schemas"]["CaptionAnimation"] | null;
            /** Verticalposition */
            verticalPosition?: number | null;
            safeArea?: components["schemas"]["SafeArea"] | null;
        };
        /**
         * TextTransform
         * @enum {string}
         */
        TextTransform: "none" | "uppercase";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Word */
        Word: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_v1_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Upload limits exceeded, or unsupported language code */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_project_api_v1_projects__project_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description A transcribe job is already queued/processing/done */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_raw_transcript_api_v1_projects__project_id__raw_transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawTranscript"];
                };
            };
            /** @description Not transcribed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ecs_api_v1_projects__project_id__ecs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ECS"];
                };
            };
            /** @description Not transcribed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_ecs_api_v1_projects__project_id__ecs_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ECSPutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ECS"];
                };
            };
            /** @description Not transcribed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (V1-V5) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_style_api_v1_projects__project_id__style_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptionStyleSpec"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_style_api_v1_projects__project_id__style_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptionStyleSpecPutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptionStyleSpec"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bounds validation failed against resolved preset */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preset"][];
                };
            };
        };
    };
    recalculate_groups_api_v1_projects__project_id__recalculate_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecalculateGroupsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecalculateGroupsResult"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolymorphicJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_to_raw_api_v1_projects__project_id__reset_to_raw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetToRawResult"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolymorphicJobResponse"];
                };
            };
            /** @description Not transcribed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_v1_projects__project_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation failed (shared with PUT /ecs, PUT /style) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_project_srt_api_v1_projects__project_id__export_srt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation failed (request body is not persisted) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
