# Mirrors faster_whisper.tokenizer._LANGUAGE_CODES (whisperx's ASR backend) as
# a static copy, not a live import - whisperx/faster-whisper are the optional
# `ml` extra (not installed in CI, see backend/pyproject.toml), so validating
# a `language` code must work without them installed. Needs manual sync if a
# future model swap changes the supported set.
SUPPORTED_LANGUAGE_CODES: frozenset[str] = frozenset(
    {
        "af",
        "am",
        "ar",
        "as",
        "az",
        "ba",
        "be",
        "bg",
        "bn",
        "bo",
        "br",
        "bs",
        "ca",
        "cs",
        "cy",
        "da",
        "de",
        "el",
        "en",
        "es",
        "et",
        "eu",
        "fa",
        "fi",
        "fo",
        "fr",
        "gl",
        "gu",
        "ha",
        "haw",
        "he",
        "hi",
        "hr",
        "ht",
        "hu",
        "hy",
        "id",
        "is",
        "it",
        "ja",
        "jw",
        "ka",
        "kk",
        "km",
        "kn",
        "ko",
        "la",
        "lb",
        "ln",
        "lo",
        "lt",
        "lv",
        "mg",
        "mi",
        "mk",
        "ml",
        "mn",
        "mr",
        "ms",
        "mt",
        "my",
        "ne",
        "nl",
        "nn",
        "no",
        "oc",
        "pa",
        "pl",
        "ps",
        "pt",
        "ro",
        "ru",
        "sa",
        "sd",
        "si",
        "sk",
        "sl",
        "sn",
        "so",
        "sq",
        "sr",
        "su",
        "sv",
        "sw",
        "ta",
        "te",
        "tg",
        "th",
        "tk",
        "tl",
        "tr",
        "tt",
        "uk",
        "ur",
        "uz",
        "vi",
        "yi",
        "yo",
        "yue",
        "zh",
    }
)

# The LLM smart re-splitter (Step 14, arch §5.3's "AI semantic splitter") is
# only attempted for languages the chosen provider/prompt has been validated
# against - all 9 confirmed members of SUPPORTED_LANGUAGE_CODES above. Any
# other language (including None/auto-detect resolving outside this set)
# skips the smart-split step entirely - no LLM call attempted, the Initial
# Splitter's dumb output stands as final.
SMART_SPLIT_LANGUAGES: frozenset[str] = frozenset(
    {"en", "ru", "uk", "pl", "fr", "es", "de", "it", "pt"}
)
