#!/usr/bin/env bash
# Allocate a stable port slot for the current git worktree and write .env.local.
#
# Worktrees isolate files, not ports/broker/database. This does the rest.
# The slot registry lives in the shared git dir, so every worktree of this repo
# sees the same allocations without any locking.
#
#   scripts/wt-env.sh          allocate (or reuse) a slot, write .env.local
#   scripts/wt-env.sh --show   print this worktree's slot and ports
#   scripts/wt-env.sh --gc     drop registry rows for worktrees that no longer exist
#
set -euo pipefail

command -v git >/dev/null || { echo "git not found" >&2; exit 1; }
TOP="$(git rev-parse --show-toplevel)"
COMMON="$(cd "$(git rev-parse --git-common-dir)" && pwd)"
REG="$COMMON/amee-slots"          # lines: "<slot>\t<worktree path>"
MAX_SLOTS=10
touch "$REG"

gc() {
  local tmp; tmp="$(mktemp)"
  while IFS=$'\t' read -r slot path; do
    [ -z "${slot:-}" ] && continue
    [ -d "$path" ] && printf '%s\t%s\n' "$slot" "$path" >> "$tmp"
  done < "$REG"
  mv "$tmp" "$REG"
  echo "registry cleaned: $(wc -l < "$REG" | tr -d ' ') slot(s) in use"
}

slot_for() {
  awk -F'\t' -v p="$TOP" '$2 == p { print $1; exit }' "$REG"
}

allocate() {
  local s; s="$(slot_for)"
  if [ -z "$s" ]; then
    for i in $(seq 0 $((MAX_SLOTS - 1))); do
      if ! awk -F'\t' -v i="$i" '$1 == i { found=1 } END { exit !found }' "$REG"; then
        s="$i"; break
      fi
    done
    [ -n "${s:-}" ] || { echo "no free slot (max $MAX_SLOTS). Run: scripts/wt-env.sh --gc" >&2; exit 1; }
    printf '%s\t%s\n' "$s" "$TOP" >> "$REG"
  fi
  echo "$s"
}

case "${1:---write}" in
  --gc)   gc; exit 0 ;;
  --show)
    s="$(slot_for)"; [ -n "$s" ] || { echo "no slot allocated for $TOP"; exit 1; }
    base=$((8000 + s * 100))
    echo "worktree : $TOP"
    echo "slot     : $s"
    echo "api      : $base"
    echo "web      : $((base+1))"
    echo "rabbitmq : $((base+2))  (mgmt $((base+3)))"
    echo "redis    : $((base+4))"
    echo "postgres : $((base+5))"
    exit 0 ;;
esac

SLOT="$(allocate)"
BASE=$((8000 + SLOT * 100))

cat > "$TOP/.env.local" <<EOF
# GENERATED by scripts/wt-env.sh — do not commit, do not copy between worktrees.
AMEE_SLOT=$SLOT
COMPOSE_PROJECT_NAME=amee-$SLOT

API_PORT=$BASE
WEB_PORT=$((BASE + 1))
RABBITMQ_PORT=$((BASE + 2))
RABBITMQ_MGMT_PORT=$((BASE + 3))
REDIS_PORT=$((BASE + 4))
POSTGRES_PORT=$((BASE + 5))

CELERY_BROKER_URL=amqp://guest:guest@localhost:$((BASE + 2))//
AMEE_DB_URL=postgresql://amee:amee@localhost:$((BASE + 5))/amee
AMEE_STORAGE_DIR=./.data/storage

VITE_API_BASE=http://localhost:$BASE/api/v1
VITE_API_MOCK=0
EOF

mkdir -p "$TOP/.data/storage"
echo "slot $SLOT -> api $BASE, web $((BASE+1)), rabbitmq $((BASE+2)).  wrote .env.local"
